django_gallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('i18n/', include('django.conf.urls.i18n')),

    path('', TemplateView.as_view(template_name='index.html')),
    path('gallery-i18n/', include('gallery_i18n.urls')),
]

# MEDIA URL
if settings.MEDIA_URL and settings.MEDIA_ROOT:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery_i18n/urls.py
from django.urls import path

from . import views

app_name = 'gallery_i18n'

urlpatterns = [
    path('', views.ExampleView.as_view(), name='example'),
    path('change-language/<str:language>', views.ChangeLanguageView.as_view(), name='change-language')
]

gallery_i18n/models.py
from django.db import models

# Create your models here.

gallery_i18n/views.py
from django.shortcuts import redirect
from django.views.generic import View, TemplateView
from django.utils import translation
from django.utils.translation import gettext as _
from django.conf import settings

class ExampleView(TemplateView):
    template_name = 'gallery_i18n/example.html'
    
    def get_context_data(self, **kwargs):
        kwargs['title_text'] = _('Hello World')
        return super().get_context_data(**kwargs)

class ChangeLanguageView(View):
    def get(self, request, *args, **kwargs):
        language = self.kwargs.get('language')
        translation.activate(language)
        if self.request.GET.get('redirect') != None:
            response = redirect(self.request.get('redirect'))
        else:
            response = redirect('gallery_i18n:example')
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language)
        return response

gallery_i18n/templates/gallery_i18n/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% load i18n %}
    <title>Internationalization Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1>{{ title_text }}</h1>
        <h2>{% trans "Hello World" %}</h2>
        <div>
            Change Languages 
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <a href="{% url 'gallery_i18n:change-language' language.code %}">{{ language.name_local }}</a> . 
            {% endfor %}
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Django Gallery</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>Django Gallery</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        html, body{
            height: 100%;
        }

        body{
            background: url('{% static 'images/django-bg.jpg' %}');
            background-position: center;
            background-size: cover;
        }

        body::before{
            content: '';
            position: absolute;
            z-index: -1;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(0, 0, 0, 0.7);
        }

        .card-link{
            height: 100%;
            text-align: center;
        }

        .card{
            background: rgba(0, 0, 0, 0.7);
            color: white;
            height: 100%;
        }
    </style>
</head>
<body>
    <div class="jumbotron text-center text-white mb-0" style="background-color: transparent;">
        <h1>Django Gallery</h1>
        <p>Django Gallery is a web based project written in Python/Django framework. It contains a collection of Django codes that helps build a project.</p> 
    </div>
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-lg-3 mb-4">
                <a href="{% url 'gallery_i18n:example' %}" class="card-link d-block text-decoration-none">
                    <div class="card">
                        <div class="card-body">
                            <h5>Internationalization</h5>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>